let contracts = {
  'Address': require('./artifacts/Address.json'),
  'AdminManaged': require('./artifacts/AdminManaged.json'),
  'Arrays': require('./artifacts/Arrays.json'),
  'BokkyPooBahsDateTimeLibrary': require('./artifacts/BokkyPooBahsDateTimeLibrary.json'),
  'CapperRole': require('./artifacts/CapperRole.json'),
  'CurveFunctions': require('./artifacts/CurveFunctions.json'),
  'CurveRegistry': require('./artifacts/CurveRegistry.json'),
  'ERC20Burnable': require('./artifacts/ERC20Burnable.json'),
  'ERC20Capped': require('./artifacts/ERC20Capped.json'),
  'ERC20Detailed': require('./artifacts/ERC20Detailed.json'),
  'ERC20': require('./artifacts/ERC20.json'),
  'ERC20Mintable': require('./artifacts/ERC20Mintable.json'),
  'ICurveFunctions': require('./artifacts/ICurveFunctions.json'),
  'ICurveRegistry': require('./artifacts/ICurveRegistry.json'),
  'IERC20': require('./artifacts/IERC20.json'),
  'IMarketFactory': require('./artifacts/IMarketFactory.json'),
  'IMarket': require('./artifacts/IMarket.json'),
  'IMarketRegistry': require('./artifacts/IMarketRegistry.json'),
  'IMoleculeVault': require('./artifacts/IMoleculeVault.json'),
  'IVault': require('./artifacts/IVault.json'),
  'MarketFactory': require('./artifacts/MarketFactory.json'),
  'Market': require('./artifacts/Market.json'),
  'MarketRegistry': require('./artifacts/MarketRegistry.json'),
  'Math': require('./artifacts/Math.json'),
  'MinterRole': require('./artifacts/MinterRole.json'),
  'MoleculeVault': require('./artifacts/MoleculeVault.json'),
  'Ownable': require('./artifacts/Ownable.json'),
  'PauserRole': require('./artifacts/PauserRole.json'),
  'PseudoDaiToken': require('./artifacts/PseudoDaiToken.json'),
  'ReentrancyGuard': require('./artifacts/ReentrancyGuard.json'),
  'Roles': require('./artifacts/Roles.json'),
  'SafeERC20': require('./artifacts/SafeERC20.json'),
  'SafeMath': require('./artifacts/SafeMath.json'),
  'Secondary': require('./artifacts/Secondary.json'),
  'SignerRole': require('./artifacts/SignerRole.json'),
  'TokenTimelock': require('./artifacts/TokenTimelock.json'),
  'Vault': require('./artifacts/Vault.json'),
  'WhitelistAdminRole': require('./artifacts/WhitelistAdminRole.json'),
  'WhitelistedRole': require('./artifacts/WhitelistedRole.json'),
};

module.exports = contracts;
