/*
 *
 * MyProjectsContainer constants
 *
 */
enum ActionTypes {
  ADD_PROJECT = 'app/projects/ADD_PROJECT',
  GET_ALL_PROJECTS = 'app/projects/GET_ALL_PROJECTS',
  GET_PROJECTS = 'app/projects/GET_PROJECTS',
  GET_MY_PROJECTS = 'app/projects/GET_MY_PROJECTS',
  LAUNCH_PROJECT_REQUEST = 'app/projects/LAUNCH_PROJECT_REQUEST',
  LAUNCH_PROJECT_SUCCESS = 'app/projects/LAUNCH_PROJECT_SUCCESS',
  LAUNCH_PROJECT_FAILURE = 'app/projects/LAUNCH_PROJECT_FAILURE',
  SUPPORT_PROJECT_REQUEST = 'app/projects/SUPPORT_PROJECT_REQUEST',
  SUPPORT_PROJECT_SUCCESS = 'app/projects/SUPPORT_PROJECT_SUCCESS',
  SUPPORT_PROJECT_FAILURE = 'app/projects/SUPPORT_PROJECT_FAILURE',
  SET_MARKET_DATA = 'app/projects/SET_MARKET_DATA',
  WITHDRAW_REDISTRIBUTION_REQUEST = "app/projects/WITHDRAW_REDISTRIBUTION_REQUEST",
  WITHDRAW_REDISTRIBUTION_SUCCESS = "app/projects/WITHDRAW_REDISTRIBUTION_SUCCESS",
  WITHDRAW_REDISTRIBUTION_FAILURE = "app/projects/WITHDRAW_REDISTRIBUTION_FAILURE",
  WITHDRAW_HOLDINGS_REQUEST = "app/projects/WITHDRAW_HOLDINGS_REQUEST",
  WITHDRAW_HOLDINGS_SUCCESS = "app/projects/WITHDRAW_HOLDINGS_SUCCESS",
  WITHDRAW_HOLDINGS_FAILURE = "app/projects/WITHDRAW_HOLDINGS_FAILURE",
  WITHDRAW_FUNDING_REQUEST = "app/projects/WITHDRAW_FUNDING_REQUEST",
  WITHDRAW_FUNDING_SUCCESS = "app/projects/WITHDRAW_FUNDING_SUCCESS",
  WITHDRAW_FUNDING_FAILURE = "app/projects/WITHDRAW_FUNDING_FAILURE",
  ADD_RESEARCH_UPDATE_REQUEST = "app/projects/ADD_RESEARCH_UPDATE_REQUEST",
  ADD_RESEARCH_UPDATE_SUCCESS = "app/projects/ADD_RESEARCH_UPDATE_SUCCESS",
  ADD_RESEARCH_UPDATE_FAILURE = "app/projects/ADD_RESEARCH_UPDATE_FAILURE",
}

export default ActionTypes;
